import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiOutlineAcademicCap,
  HiOutlineCircleStack,
  HiOutlineCodeBracketSquare,
  HiOutlineCog6Tooth,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiDevicePhoneMobile,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineMagnifyingGlass,
  HiOutlineLockClosed,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineShoppingCart,
  HiOutlineWrenchScrewdriver,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiBootstrap,
  SiTailwindcss,
  SiReact,
  SiVuedotjs,
  SiPhp,
  SiLaravel,
  SiSymfony,
  SiNodedotjs,
  SiMysql,
  SiGit,
  SiShopify,
  SiPrestashop,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
} from "react-icons/si";

import { FaCarSide, FaDiscord, FaGithub, FaLinkedin, FaWordpress, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  code: HiOutlineCodeBracketSquare,
  database: HiOutlineCircleStack,
  tools: HiOutlineWrenchScrewdriver,
  seo: HiOutlineMagnifyingGlass,
  education: HiOutlineAcademicCap,
  settings: HiOutlineCog6Tooth,
  cart: HiOutlineShoppingCart,
  email: HiEnvelope,
  phone: HiDevicePhoneMobile,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  wordpress: FaWordpress,
  car: FaCarSide,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  html: SiHtml5,
  css: SiCss3,
  bootstrap: SiBootstrap,
  tailwind: SiTailwindcss,
  react: SiReact,
  vue: SiVuedotjs,
  php: SiPhp,
  laravel: SiLaravel,
  symfony: SiSymfony,
  nodejs: SiNodedotjs,
  mysql: SiMysql,
  git: SiGit,
  shopify: SiShopify,
  prestashop: SiPrestashop,
  dns: HiOutlineGlobeAsiaAustralia,
  ssl: HiOutlineLockClosed,
  ftp: HiOutlineWrenchScrewdriver,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
