// Generated by scripts/build_english.mjs; edit the shared layout or scripts/translations-en.json.
"use client";

import { useState } from "react";
import Link from "next/link";
import { Media } from "@once-ui-system/core";
import styles from "@/components/work/PortfolioExplorer.module.scss";

type Project = {
  slug: string;
  metadata: { title: string; subtitle?: string; summary: string; images: string[]; product: string; development: string; stack: string };
};

const filters = ["All", "Applications & product", "WordPress & e-commerce", "Front-end & integration"];
const groups: Record<string, string[]> = {
  "Applications & product": ["bridge-it", "pro-pattes"],
  "WordPress & e-commerce": ["canissimo-en-ligne", "web-adn", "rouf-wouf"],
  "Front-end & integration": ["bridge-it", "web-adn", "adms-plus"],
};

export function PortfolioExplorer({ projects }: { projects: Project[] }) {
  const [filter, setFilter] = useState("All");
  const visible = projects.filter(project => filter === "All" || groups[filter].includes(project.slug));

  return (
    <section id="projets" className={styles.section} aria-labelledby="projects-title">
      <div className={styles.sectionHeader}>
        <div><p className={styles.eyebrow}>{"Different needs, the same commitment to quality"}</p><h2 id="projects-title">{"Selected projects"}</h2></div>
        <p>{"Explore the context, my role and my contributions to each assignment."}</p>
      </div>
      <div className={styles.filters} role="group" aria-label="Filter projects by category">
        {filters.map(item => <button type="button" key={item} aria-pressed={filter === item} onClick={() => setFilter(item)}>{item}</button>)}
      </div>
      <p className={styles.count} role="status" aria-live="polite" aria-atomic="true">{visible.length} project{visible.length !== 1 ? "s" : ""} shown out of {projects.length}</p>
      <div className={styles.grid}>
        {visible.map(project => (
          <article key={project.slug} className={styles.card}>
            {project.metadata.images[0] ? <div className={styles.preview}><Media src={project.metadata.images[0]} alt={`Project preview: ${project.metadata.title}`} aspectRatio="16 / 9" sizes="(max-width: 700px) 100vw, 480px" /></div> :
              <div className={`${styles.preview} ${styles.typographic}`} aria-hidden="true"><span>{project.metadata.subtitle}</span><strong>{project.metadata.title}</strong><span>{"Design · Development"}</span></div>}
            <div className={styles.cardBody}>
              <p className={styles.eyebrow}>{project.metadata.subtitle}</p>
              <h3><Link href={`/en/work/${project.slug}`}>{project.metadata.title}<span aria-hidden="true"> ↗</span></Link></h3>
              <p className={styles.summary}>{project.metadata.summary}</p>
              <dl className={styles.contributions}>
                <div><dt>{"Project & product"}</dt><dd>{project.metadata.product}</dd></div>
                <div><dt>{"Development"}</dt><dd>{project.metadata.development}</dd></div>
              </dl>
              <p className={styles.stack}><span className={styles.srOnly}>{"Technologies: "}</span>{project.metadata.stack}</p>
              <Link className={styles.caseLink} href={`/en/work/${project.slug}`} aria-label={`Explore the project ${project.metadata.title}`}>{"Explore the project "}<span aria-hidden="true">→</span></Link>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
