// Generated by scripts/build_english.mjs; edit the shared layout or scripts/translations-en.json.
import { Column, Heading, Line, Meta, Row, Schema, SmartLink, Text } from "@once-ui-system/core";
import { baseURL, person } from "@/locales/en/resources";
import TallyEmbed from "./TallyEmbed";
import CalEmbed from "./CalEmbed";

const path = "/en/contact";

export async function generateMetadata() {
  const title = `Contact – ${person.name}`;
  const description = "Contact me about a project, an assignment or an opportunity.";

  return Meta.generate({
    title,
    description,
    baseURL,
    path,
    image: "/images/og/home.jpg",
  });
}

export default function ContactPage() {
  const title = `Contact`;
  const description = "Tell me what you need and I will get back to you as soon as possible.";

  return (
    <Column maxWidth="m" gap="xl" paddingY="12" horizontal="center">
      <Schema
        as="webPage"
        baseURL={baseURL}
        path={path}
        title={`${title} – ${person.name}`}
        description={description}
        image="/images/og/home.jpg"
        author={{
          name: person.name,
          url: `${baseURL}${path}`,
          image: `${baseURL}${person.avatar}`,
        }}
      />

      <Column fillWidth maxWidth="s" gap="m" paddingX="l">
        <Heading wrap="balance" variant="display-strong-l">
          {title}
        </Heading>
        <Text wrap="balance" onBackground="neutral-weak" variant="heading-default-l">
          {description}
        </Text>

        <TallyEmbed />

        <Row fillWidth paddingY="24">
          <Line />
        </Row>

        <Heading wrap="balance" variant="heading-strong-l">
          {"Book a call"}</Heading>
        <Text wrap="balance" onBackground="neutral-weak" variant="body-default-m">
          {"Choose a time directly in my calendar."}</Text>
        <CalEmbed />

        <Row fillWidth paddingY="24">
          <Line />
        </Row>

        <Text variant="body-default-s" onBackground="neutral-weak">
          {"Or by email: "}{" "}
          <SmartLink href={`mailto:${person.email}`} suffixIcon="arrowUpRightFromSquare">
            {person.email}
          </SmartLink>
        </Text>
      </Column>
    </Column>
  );
}
