// Generated by scripts/build_english.mjs; edit the shared layout or scripts/translations-en.json.
import { Meta } from "@once-ui-system/core";
import { baseURL, about } from "@/locales/en/resources";
import AboutPage from "@/locales/en/components/about/AboutPage";

export async function generateMetadata() {
  return Meta.generate({
    title: about.title,
    description: about.description,
    baseURL,
    image: "/images/og/home.jpg",
    path: about.path,
  });
}

export default function About() {
  return <AboutPage about={about} />;
}
