// Generated by scripts/build_english.mjs; edit the shared layout or scripts/translations-en.json.
import type { About } from "@/types";
import { about, person } from "./content";
import profiles from "./cv-profiles.json";

export function getAboutProfile(mode: "tech" | "project"): About {
  const profile = profiles[mode];
  const technical = mode === "tech";
  return {
    ...about,
    path: technical ? "/en/about/developpeur-full-stack" : "/en/about/chef-de-projet",
    label: technical ? "About · Full-stack development" : "About · Project management",
    title: `${profile.role} – ${person.name}`,
    description: profile.intro,
    tagline: technical ? "Web development, code quality and user experience" : "Scoping, planning and tracking web projects",
    intro: { ...about.intro, description: profile.intro },
    work: {
      ...about.work,
      experiences: about.work.experiences.map((experience, index) => ({
        ...experience,
        achievements: profile.achievements[index],
      })),
    },
    studies: {
      ...about.studies,
      institutions: about.studies.institutions.map((institution, index) => ({
        ...institution,
        description: <>
          {index === 0 ? "IT-AKADEMY / 2019 - 2021 • French RNCP level 6 • Apprenticeship" : "OPENCLASSROOMS / 2018 - 2019 • French RNCP level 5 qualification"}
          <ul>{profile.education[index]
            .filter((detail) => !technical || !detail.startsWith("Project management:"))
            .map((detail) => <li key={detail}>{detail}</li>)}</ul>
        </>,
      })),
    },
    technical: {
      ...about.technical,
      skills: profile.skills.map(([title, description]) => ({
        title,
        description,
        tags: description.split(/[,\n]/).map((name) => ({ name: name.trim() })),
      })),
    },
  };
}
