// Generated by scripts/build_english.mjs; edit the shared layout or scripts/translations-en.json.
import { About, Home, Newsletter, Person, Social, Work } from "@/types";
import { Line, Row, Text } from "@once-ui-system/core";

const person: Person = {
  firstName: "Manon",
  lastName: "Gomez Mor",
  name: "Manon Gomez Mor",
  role: "IT Project Manager | Web Project Management | Full-Stack Developer",
  avatar: "/images/avatar.jpg",
  email: "manongomezdev@gmail.com",
  phone: "07 82 95 66 21",
  location: "Aix-les-Bains",
  timeZone: "Europe/Paris",
  languages: ["French", "English"],
};

const newsletter: Newsletter = {
  display: false,
  title: <>Newsletter</>,
  description: <>{"Subscribe to the newsletter"}</>,
};

const social: Social = [
  // Links are automatically displayed.
  // Import new icons in /once-ui/icons.ts
  // Set essentials: true for links you want to show on the about page
  {
    name: "LinkedIn",
    icon: "linkedin",
    link: "https://www.linkedin.com/in/manongomez-mor-251b0b170",
    essential: false,
  },
  {
    name: "GitHub",
    icon: "github",
    link: "",
    essential: false,
  },
  {
    name: "Threads",
    icon: "threads",
    link: "",
    essential: false,
  },
  {
    name: "Email",
    icon: "email",
    link: `mailto:${person.email}`,
    essential: false,
  },
];

const home: Home = {
  path: "/en",
  image: "/images/og/home.jpg",
  label: "Home",
  title: `Portfolio – ${person.name}`,
  description: "Full-stack developer: designing, building and managing web projects, from requirements to launch.",
  headline: <>{"Bring your dream website to life, from design to launch"}</>,
  featured: {
    display: false,
    title: <Row />,
    href: "/en/work",
  },
  subline: (
    <>
      {"I'm"}{" "}
      <Text as="span" size="xl" weight="strong">
        {person.firstName}
      </Text>
      {", a"}{" "}
      <Text as="span" size="xl" weight="strong">
        Full-Stack
      </Text>{" "}
      {"developer specialising in designing and building web projects."}</>
  ),
};

const about: About = {
  path: "/en/about",
  label: "About",
  title: `About – ${person.name}`,
  description:
    "Manon Gomez Mor: full-stack development and web project management since 2019. Experience, technical skills, project management and education.",
  tableOfContent: { display: true, subItems: false },
  avatar: { display: true },
  calendar: { display: false, link: "" },
  tagline: "From business requirements to launch",
  intro: {
    display: true,
    title: "Introduction",
    description: (
      <>
        {"A full-stack developer since 2019, I design, build and manage websites, web platforms and online stores. My agency, team and freelance experience combines front-end and back-end development, scoping, cost estimation, planning and client communication."}<br />
        <br />
        {"I enjoy connecting business expectations, user needs and technical constraints to deliver useful, lasting solutions. Teaching and mentoring have strengthened my ability to explain, support and help others progress. I would like to bring this experience to a team in full-stack development or IT and product project management."}</>
    ),
  },
  work: {
    display: true,
    title: "Experience",
    experiences: [
      {
        company: "Freelance",
        timeframe: "February 2022 - Present",
        role: "Full-stack Developer",
        logo: "/images/about/freelance.png",
        highlights: ["Over 34 projects completed"],
        achievements: [
          "Clarify client requests and turn goals, user needs and constraints into functional and technical solutions.",
          "Define project scope: review existing systems, advise clients, estimate work and costs, and prepare proposals.",
          "Plan stages, organise priorities and hold progress meetings to present work, gather feedback and adjust solutions.",
          "Build custom websites, platforms and online stores: front-end, back-end and third-party service integration.",
          "Maintain applications: investigate incidents, fix bugs and improve performance and user experience.",
          "Tools and technologies: PHP, JavaScript, React, Next.js, Laravel, Tailwind CSS, WordPress, WooCommerce, Shopify and MySQL.",
          "Carry out acceptance testing and deployment; train clients and provide technical support.",
        ],
      },
      {
        company: "IT-Akademy",
        timeframe: "January 2023 - April 2026",
        role: "Web development instructor",
        logo: "/images/about/it-akademy.png",
        highlights: ["Over 17 sessions • Over 255 students"],
        achievements: [
          "Taught HTML/CSS, JavaScript, procedural and object-oriented PHP, WordPress and WooCommerce to higher education students.",
          "Designed practical exercises and helped students solve technical problems, adapting teaching to their skill levels.",
          "Shared good practices in code quality, accessibility and UX, along with specification writing.",
          "Taught requirements analysis, specification writing and cost estimation to higher education students.",
        ],
      },
      {
        company: "OpenClassrooms",
        timeframe: "October 2022 - December 2024",
        role: "Mentor",
        logo: "/images/about/openclassrooms.png",
        highlights: ["Over 30 students supported"],
        achievements: [
          "Helped WordPress development and web integration students analyse project difficulties and find solutions.",
          "Reviewed their work and shared good practices in development, quality and work planning.",
          "Adapted support and feedback to each student’s difficulties to help them build skills and work independently.",
        ],
      },
      {
        company: "CISS",
        timeframe: "May 2022 - November 2022",
        role: "Front-end developer",
        logo: "/images/about/ciss.png",
        highlights: [],
        achievements: [
          "Developed features and fixes in Vue.js and Laravel as part of payment solution maintenance.",
          "Analysed and tracked tickets using Kanban; designed interfaces in Figma and worked with Git, SVN and code reviews.",
        ],
      },
      {
        company: "Synolia",
        timeframe: "September 2021 - March 2022",
        role: "Symfony / Sylius developer",
        logo: "/images/about/synolia.png",
        highlights: [],
        achievements: [
          "Maintained and improved several e-commerce projects using Symfony / Sylius, PHP and Twig, following specifications.",
          "Analysed and estimated tickets; worked in Scrum with Jira, Git and code reviews.",
          "Developed with Symfony / Sylius following backlog priorities; took part in sprint planning and retrospectives.",
        ],
      },
      {
        company: "Cyloé",
        timeframe: "August 2019 - September 2021",
        role: "Web developer",
        logo: "/images/about/cyloe.png",
        highlights: [],
        achievements: [
          "Built websites and online stores with WordPress, WooCommerce, Shopify, WiziShop, Joomla and PHP.",
          "Managed hosting, configuration and deployment; carried out acceptance testing, fixes and feature updates.",
          "Improved SEO, performance and layouts across screen sizes; trained clients and solved technical incidents.",
          "Managed several client projects independently: requirements, work planning, priorities and deadlines.",
        ],
      },
    ],
  },
  studies: {
    display: true,
    title: "Education",
    institutions: [
      {
        name: "Mastère 1 - Full-stack\nApplication Development",
        logo: "/images/about/it-akademy.png",
        description: (
          <>
            {"IT-AKADEMY / 2019 - 2021 • French RNCP level 6 • Apprenticeship"}
            <ul>
              <li>
                {
                  "Web development and OOP: PHP, JavaScript, Node.js, Python, Java, APIs, frameworks and design patterns."
                }
              </li>
              <li>
                {
                  "Database design, management and optimisation; software architecture, security and performance."
                }
              </li>
              <li>
                {
                  "Project management: gathering needs, writing specifications, estimating costs, planning and coordination."
                }
              </li>
              <li>{"Methods and tools: software quality, DevOps, AWS cloud, UX design, SEO and e-commerce."}</li>
            </ul>
          </>
        ),
      },
      {
        name: "Web developer",
        logo: "/images/about/openclassrooms.png",
        description: (
          <>
            {"OPENCLASSROOMS / 2018 - 2019 • French RNCP level 5 qualification"}
            <ul>
              <li>{"Responsive website development with HTML5/CSS3."}</li>
              <li>
                {"Dynamic JavaScript features and API integration."}
              </li>
              <li>
                {
                  "Object-oriented programming, error handling and good development practices."
                }
              </li>
              <li>{"Database design and management."}</li>
              <li>{"SEO, performance and compatibility across screen sizes."}</li>
            </ul>
          </>
        ),
      },
    ],
  },
  technical: {
    display: true,
    title: "Skills",
    skills: [
      {
        title: "Project management",
        description:
          "Analyse requirements, define scope and costs, organise priorities and track delivery. Agile, Scrum and Kanban methods.",
        tags: [
          {
            name: "Requirements analysis",
          },
          {
            name: "Existing system review",
          },
          {
            name: "Functional and technical specifications",
          },
          {
            name: "Project specifications",
          },
          {
            name: "Effort estimation",
          },
          {
            name: "Cost estimation & proposals",
          },
          {
            name: "Planning",
          },
          {
            name: "Prioritisation",
          },
          {
            name: "Progress tracking",
          },
          {
            name: "Acceptance testing",
          },
          {
            name: "Client communication",
          },
          {
            name: "Agile",
          },
          {
            name: "Scrum",
          },
          {
            name: "Kanban",
          },
          {
            name: "Code reviews",
          },
          {
            name: "Jira",
            icon: "jira",
          },
          {
            name: "Linear",
            icon: "linear",
          },
        ],
      },
      {
        title: "Web development",
        description:
          "Design and maintain websites, applications and online stores: interfaces, back-end, databases and API integration.",
        tags: [
          {
            name: "HTML5",
            icon: "html",
          },
          {
            name: "CSS3",
            icon: "css",
          },
          {
            name: "JavaScript",
            icon: "javascript",
          },
          {
            name: "React",
            icon: "react",
          },
          {
            name: "Next.js",
            icon: "nextjs",
          },
          {
            name: "Vue.js",
            icon: "vue",
          },
          {
            name: "Tailwind CSS",
            icon: "tailwind",
          },
          {
            name: "Bootstrap",
            icon: "bootstrap",
          },
          {
            name: "PHP",
            icon: "php",
          },
          {
            name: "Laravel",
            icon: "laravel",
          },
          {
            name: "Symfony",
            icon: "symfony",
          },
          {
            name: "Sylius",
            icon: "sylius",
          },
          {
            name: "Twig",
            icon: "code",
          },
          {
            name: "MySQL",
            icon: "mysql",
          },
          {
            name: "REST APIs",
            icon: "code",
          },
          {
            name: "WordPress",
            icon: "wordpress",
          },
          {
            name: "WooCommerce",
            icon: "woocommerce",
          },
          {
            name: "Shopify",
            icon: "shopify",
          },
          {
            name: "WiziShop",
            icon: "cart",
          },
          {
            name: "Joomla",
            icon: "joomla",
          },
        ],
      },
      {
        title: "Tools & automation",
        description: "Prototyping, version control, deployment, optimisation and AI tools.",
        tags: [
          {
            name: "Figma",
            icon: "figma",
          },
          {
            name: "Git",
            icon: "git",
          },
          {
            name: "SVN",
            icon: "svn",
          },
          {
            name: "DNS",
            icon: "dns",
          },
          {
            name: "SSL",
            icon: "ssl",
          },
          {
            name: "FTP",
            icon: "ftp",
          },
          {
            name: "SEO",
            icon: "seo",
          },
          {
            name: "Performance",
            icon: "settings",
          },
          {
            name: "n8n",
            icon: "n8n",
          },
          {
            name: "ChatGPT",
            icon: "openai",
          },
          {
            name: "Claude",
            icon: "claude",
          },
          {
            name: "Claude Code",
            icon: "claude",
          },
          {
            name: "Codex",
            icon: "openai",
          },
          {
            name: "Cursor",
            icon: "cursor",
          },
        ],
      },
      {
        title: "Soft skills",
        description: "Organise, communicate and support clients and teams.",
        tags: [
          {
            name: "Organisation",
          },
          {
            name: "Attention to detail",
          },
          {
            name: "Independence",
          },
          {
            name: "Communication",
          },
          {
            name: "Teaching",
          },
          {
            name: "Problem solving",
          },
        ],
      },
    ],
  },
};

const work: Work = {
  path: "/en/work",
  label: "Portfolio",
  title: `Projects – ${person.name}`,
  description: "Six selected projects: web development, functional design and project management, from requirements to launch.",
  // Create new project pages by adding a new .mdx file to app/blog/posts
  // All projects will be listed on the /home and /work routes
};

export { person, social, newsletter, home, about, work };
