// Generated by scripts/build_english.mjs; edit the shared layout or scripts/translations-en.json.
import { Column, Heading, Line, Meta, Row, Schema, SmartLink, Text } from "@once-ui-system/core";
import { baseURL, person } from "@/locales/en/resources";

const path = "/en/mentions-legales";

export async function generateMetadata() {
  const title = `Legal notice – ${person.name}`;
  const description = `Legal notice and website hosting information for ${person.name}.`;

  return Meta.generate({
    title,
    description,
    baseURL,
    path,
    image: "/images/og/home.jpg",
  });
}

export default function MentionsLegalesPage() {
  const title = "Legal notice";

  return (
    <Column maxWidth="m" gap="xl" paddingY="12" horizontal="center">
      <Schema
        as="webPage"
        baseURL={baseURL}
        path={path}
        title={`${title} – ${person.name}`}
        description={`Legal notice and website hosting information for ${person.name}.`}
        image="/images/og/home.jpg"
        author={{
          name: person.name,
          url: `${baseURL}${path}`,
          image: `${baseURL}${person.avatar}`,
        }}
      />

      <Column fillWidth maxWidth="s" gap="m" paddingX="l">
        <Heading wrap="balance" variant="display-strong-l">
          {title}
        </Heading>
        <Text wrap="balance" onBackground="neutral-weak" variant="body-default-m">
          {"In accordance with applicable regulations, the following information identifies the publisher, hosting provider and operation of this portfolio website."}</Text>

        <Row fillWidth paddingY="24">
          <Line />
        </Row>

        <Heading wrap="balance" variant="heading-strong-l">
          {"Website publisher"}</Heading>
        <Column gap="8">
          <Text variant="body-default-m" onBackground="neutral-weak">
            <Text as="span" onBackground="neutral-weak">
              {"Website type: "}{" "}
            </Text>
            {"Business presentation and portfolio website, with no online sales."}</Text>
          <Text variant="body-default-m">
            <Text as="span" onBackground="neutral-weak">
              {"Business name: "}{" "}
            </Text>
            {person.name}
          </Text>
          <Text variant="body-default-m">
            <Text as="span" onBackground="neutral-weak">
              {"Publication director: "}{" "}
            </Text>
            Manon Gomez Mor
          </Text>
          <Text variant="body-default-m">
            <Text as="span" onBackground="neutral-weak">
              {"Email: "}{" "}
            </Text>
            <SmartLink href={`mailto:${person.email}`} suffixIcon="arrowUpRightFromSquare">
              {person.email}
            </SmartLink>
          </Text>
        </Column>

        <Row fillWidth paddingY="24">
          <Line />
        </Row>

        <Heading wrap="balance" variant="heading-strong-l">
          {"Hosting provider"}</Heading>
        <Column gap="8">
          <Text variant="body-default-m">
            <Text as="span" onBackground="neutral-weak">
              {"Hosting provider: "}{" "}
            </Text>
            Cloudflare, Inc.
          </Text>
          <Text variant="body-default-m">
            <Text as="span" onBackground="neutral-weak">
              {"Address: "}{" "}
            </Text>
            {"101 Townsend St, San Francisco, CA 94107, United States"}</Text>
          <Text variant="body-default-m">
            <Text as="span" onBackground="neutral-weak">
              {"Website: "}{" "}
            </Text>
            <SmartLink href="https://www.cloudflare.com" suffixIcon="arrowUpRightFromSquare">
              www.cloudflare.com
            </SmartLink>
          </Text>
        </Column>

        <Row fillWidth paddingY="24">
          <Line />
        </Row>

        <Heading wrap="balance" variant="heading-strong-l">
          {"Intellectual property"}</Heading>
        <Column gap="8">
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"Unless otherwise stated, all content on this website (text, images, illustrations, graphics, logos, icons, videos, animations, code, etc.) is owned by "}{person.name} {" and protected by copyright and intellectual property law."}</Text>
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"Reproduction, display, modification, publication or adaptation of all or part of this content, on any medium, is prohibited without prior written permission."}</Text>
        </Column>

        <Row fillWidth paddingY="24">
          <Line />
        </Row>

        <Heading wrap="balance" variant="heading-strong-l">
          {"Liability"}</Heading>
        <Column gap="8">
          <Text variant="body-default-m" onBackground="neutral-weak">
            {person.name} {" aims to provide information that is as accurate as possible. However, "}{person.name} {" cannot guarantee the accuracy, completeness or currency of the information published on this website."}</Text>
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"Visitors use this website at their own responsibility. "}{person.name} {" cannot be held liable for direct or indirect damage (data loss, business interruption, etc.) resulting from access to or use of this website."}</Text>
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"Links to third-party websites may be provided. "}{person.name} {" has no control over these websites and cannot be held responsible for their content or practices."}</Text>
        </Column>

        <Row fillWidth paddingY="24">
          <Line />
        </Row>

        <Heading wrap="balance" variant="heading-strong-l">
          {"Personal data (GDPR)"}</Heading>
        <Column gap="8">
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"The data controller is: "}{person.name}{". Data that may be collected mainly consists of information voluntarily provided by visitors (for example through the contact form or appointment booking) to answer requests and follow up on conversations."}</Text>
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"Data is retained for the time needed to process the request, then archived or deleted according to applicable legal obligations."}</Text>
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"Service providers and third parties involved depending on your use of the website:"}</Text>
          <Column gap="8" paddingLeft="12">
            <Text variant="body-default-m" onBackground="neutral-weak">
              {"- Hosting/CDN: Cloudflare"}</Text>
            <Text variant="body-default-m" onBackground="neutral-weak">
              {"- Embedded contact form: "}{" "}
              <SmartLink href="https://tally.so" suffixIcon="arrowUpRightFromSquare">
                Tally
              </SmartLink>
            </Text>
            <Text variant="body-default-m" onBackground="neutral-weak">
              {"- Appointment booking: "}{" "}
              <SmartLink href="https://cal.com" suffixIcon="arrowUpRightFromSquare">
                Cal.com
              </SmartLink>
            </Text>
          </Column>
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"Under the GDPR, you have rights of access, rectification, erasure, restriction, objection and portability. To exercise these rights, contact: "}{" "}
            <SmartLink href={`mailto:${person.email}`} suffixIcon="arrowUpRightFromSquare">
              {person.email}
            </SmartLink>
            {". You may also lodge a complaint with the French data protection authority (CNIL)."}</Text>
        </Column>

        <Row fillWidth paddingY="24">
          <Line />
        </Row>

        <Heading wrap="balance" variant="heading-strong-l">
          {"Cookies and trackers"}</Heading>
        <Column gap="8">
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"This website may use cookies or trackers strictly necessary for its operation. Depending on the third-party services embedded (such as Tally forms, Cal.com calendars or Cloudflare services), technical or audience measurement cookies may also be set."}</Text>
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"You can configure your browser to reject some or all cookies. Rejecting certain cookies may affect access to features such as the contact form or appointment booking."}</Text>
        </Column>

        <Row fillWidth paddingY="24">
          <Line />
        </Row>

        <Heading wrap="balance" variant="heading-strong-l">
          {"Governing law"}</Heading>
        <Column gap="8">
          <Text variant="body-default-m" onBackground="neutral-weak">
            {"This legal notice is governed by French law. If a dispute cannot be resolved amicably, the competent courts will be those with jurisdiction over the publisher's place of residence, unless mandatory legal provisions require otherwise."}</Text>
        </Column>
      </Column>
    </Column>
  );
}
