// Generated by scripts/build_english.mjs; edit the shared layout or scripts/translations-en.json.
import { Meta } from "@once-ui-system/core";
import { getAboutProfile } from "@/locales/en/resources/about-profiles";
import profiles from "@/locales/en/resources/cv-profiles.json";
import AboutPage from "@/locales/en/components/about/AboutPage";

const about = getAboutProfile("project");

export async function generateMetadata() {
  return Meta.generate({
    title: about.title,
    description: about.description,
    baseURL: "https://manongomezmor.fr",
    image: "/images/og/home.jpg",
    path: about.path,
  });
}

export default function Profile() {
  return <AboutPage
    about={about}
    siteBaseURL="https://manongomezmor.fr"
    role={profiles.project.role}
    cv="/files/CV-Manon-Gomez-Mor-PROJECT-EN.pdf"
    contactMessage="An IT or product project management role? Let's discuss your team's needs."
  />;
}
