// Generated by scripts/build_english.mjs; edit the shared layout or scripts/translations-en.json.
import { Button, Column, Meta, Schema } from "@once-ui-system/core";
import { baseURL, about, person, work } from "@/locales/en/resources";
import { PortfolioExplorer } from "@/locales/en/components/work/PortfolioExplorer";
import { getPosts } from "@/utils/utils";
import styles from "@/app/work/page.module.scss";

export async function generateMetadata() {
  return Meta.generate({ title: work.title, description: work.description, baseURL, image: "/images/og/home.jpg", path: work.path });
}

export default function Work() {
  const projects = getPosts(["src", "locales", "en", "projects"]).filter(post => post.metadata.selected).sort((a, b) => a.metadata.order - b.metadata.order);
  return (
    <Column maxWidth="m" paddingTop="24" gap="40" className={styles.page}>
      <Schema as="webPage" baseURL={baseURL} path={work.path} title={work.title} description={work.description} image="/images/og/home.jpg" author={{ name: person.name, url: `${baseURL}${about.path}`, image: `${baseURL}${person.avatar}` }} />
      <section className={styles.hero} aria-labelledby="portfolio-title">
        <p className={styles.eyebrow}>{"Portfolio · Development, projects & product"}</p>
        <h1 id="portfolio-title">{"Web projects,"}<br />{"from requirements to launch."}</h1>
        <p className={styles.intro}>{"As a freelancer and alongside different teams, I have worked on "}<strong>{"more than 34 web projects"}</strong> {" : business applications, learning platforms, online stores, business and corporate websites, interactive interfaces, maintenance and optimisation."}</p>
        <p className={styles.intro}>{"Depending on the requirements, my work covers advice, design, development, testing, deployment and user support. These six projects illustrate how I connect business challenges with technical implementation."}</p>
        <div className={styles.actions}>
          <Button href="#projets" variant="primary" size="m" arrowIcon>{"Explore the 6 projects"}</Button>
          <Button href={about.path} variant="secondary" size="m">{"Explore my background"}</Button>
        </div>
        <div className={styles.approach}>
          <div><span>{"01 / Understand"}</span><p>{"Analyse requirements and user needs to define a suitable solution."}</p></div>
          <div><span>{"02 / Build"}</span><p>{"Design user journeys and develop interfaces and business logic."}</p></div>
          <div><span>{"03 / Support"}</span><p>{"Test, deploy and improve tools according to the assignment."}</p></div>
        </div>
      </section>
      <PortfolioExplorer projects={projects.map(({ slug, metadata }) => ({ slug, metadata }))} />
      <section className={styles.contact} aria-labelledby="contact-title">
        <div><p className={styles.eyebrow}>{"A project to build or a team to join?"}</p><h2 id="contact-title">{"Let's discuss your needs."}</h2><p>{"A development assignment, a web project to manage or a product role: let's discuss the needs of your business and your team."}</p></div>
        <Button href="/en/contact" variant="primary" size="m" arrowIcon>{"Get in touch"}</Button>
      </section>
    </Column>
  );
}
