// Generated by scripts/build_english.mjs; edit the shared layout or scripts/translations-en.json.
import {
  Heading,
  Text,
  Button,
  Avatar,
  Flex,
  Column,
  Badge,
  Row,
  Icon,
  Card,
  Grid,
  Schema,
  Meta,
  Line,
} from "@once-ui-system/core";
import { home, about, person, baseURL } from "@/locales/en/resources";
import styles from "@/app/page.module.scss";

export async function generateMetadata() {
  return Meta.generate({
    title: home.title,
    description: home.description,
    baseURL: baseURL,
    path: home.path,
    image: home.image,
  });
}

export default function Home() {
  return (
    <Column maxWidth="m" gap="xl" paddingY="12" horizontal="center">
      <Schema
        as="webPage"
        baseURL={baseURL}
        path={home.path}
        title={home.title}
        description={home.description}
        image={home.image}
        author={{
          name: person.name,
          url: `${baseURL}${about.path}`,
          image: `${baseURL}${person.avatar}`,
        }}
      />
      <Column fillWidth horizontal="center" gap="m">
        <Column maxWidth="s" horizontal="center" align="center">
          <Flex fillWidth horizontal="center" paddingTop="16" paddingBottom="24">
            <Badge
              background="brand-alpha-weak"
              paddingX="12"
              paddingY="4"
              onBackground="neutral-strong"
              textVariant="label-default-s"
              arrow={false}
            >
              {"✅ Full-Stack Development • Project Management • Product"}</Badge>
          </Flex>

          <Flex fillWidth horizontal="center" paddingBottom="16">
            <Heading wrap="balance" variant="display-strong-l">
              {home.headline}
            </Heading>
          </Flex>

          <Flex fillWidth horizontal="center" paddingBottom="16">
            <Text wrap="balance" onBackground="neutral-weak" variant="heading-default-xl">
              {home.subline}
            </Text>
          </Flex>

          <Flex fillWidth horizontal="center" paddingBottom="24">
            <Text wrap="balance" onBackground="neutral-weak" variant="body-default-l">
              {"From defining requirements to launch, I work across the entire project lifecycle: advice, solution selection, design, development, progress tracking, acceptance testing, deployment and user support."}</Text>
          </Flex>

          <Flex fillWidth horizontal="center" paddingBottom="24">
            <Text wrap="balance" onBackground="neutral-weak" variant="body-default-l">
              {"My technical background helps me build solutions, understand their challenges, anticipate constraints and connect business requirements with implementation."}</Text>
          </Flex>

          <Flex fillWidth horizontal="center" paddingBottom="24">
            <Row gap="12" wrap horizontal="center">
              <Badge background="surface" border="neutral-alpha-weak" radius="full" paddingX="12" paddingY="4">
                <Row gap="8" vertical="center">
                  <Icon name="rocket" onBackground="brand-weak" />
                  <Text variant="label-default-s">{"Design"}</Text>
                </Row>
              </Badge>
              <Badge background="surface" border="neutral-alpha-weak" radius="full" paddingX="12" paddingY="4">
                <Row gap="8" vertical="center">
                  <Icon name="settings" onBackground="brand-weak" />
                  <Text variant="label-default-s">{"Develop"}</Text>
                </Row>
              </Badge>
              <Badge background="surface" border="neutral-alpha-weak" radius="full" paddingX="12" paddingY="4">
                <Row gap="8" vertical="center">
                  <Icon name="code" onBackground="brand-weak" />
                  <Text variant="label-default-s">{"Manage"}</Text>
                </Row>
              </Badge>
            </Row>
          </Flex>

          <Flex paddingTop="12" horizontal="center" paddingLeft="12">
            <Row gap="12" wrap horizontal="center">
              <Button
                id="contact"
                data-border="rounded"
                href="/en/contact"
                variant="primary"
                size="m"
                weight="default"
                arrowIcon
              >
                {"📩 Discuss your project"}</Button>
              <Button
                id="portfolio"
                data-border="rounded"
                href="/en/work"
                variant="secondary"
                size="m"
                weight="default"
                arrowIcon
              >
                {"View my work"}</Button>
              <Button
                id="about"
                data-border="rounded"
                href={about.path}
                variant="secondary"
                size="m"
                weight="default"
                arrowIcon
              >
                <Row gap="8" vertical="center" paddingRight="4">
                  {about.avatar.display && (
                    <Avatar
                      marginRight="8"
                      style={{ marginLeft: "-0.75rem" }}
                      src={person.avatar}
                      size="m"
                    />
                  )}
                  {"About"}</Row>
              </Button>
            </Row>
          </Flex>
        </Column>
      </Column>

      <Flex fillWidth>
        <Column as="section" fillWidth gap="24" paddingX="l">
          <Row fillWidth horizontal="center" marginBottom="8">
            <Row gap="12" vertical="center">
              <Icon name="rocket" onBackground="brand-weak" />
              <Heading as="h2" variant="display-strong-xs" wrap="balance">{"From idea to launch"}</Heading>
              <Line background="brand-alpha-weak" flex={1} />
            </Row>
          </Row>
          <Text onBackground="neutral-weak" variant="body-default-l">
            {"A web project starts before the first line of code. I support each project as a whole, from understanding requirements to helping users get started."}</Text>
          <Grid fillWidth gap="12" columns={2} s={{ columns: 1 }}>
            <Card className={styles.skillCard} fillWidth background="surface" border="brand-alpha-weak" radius="l" padding="m" shadow="m">
              <Column className={styles.skillCardContent} fillWidth gap="12">
                <Row gap="12" vertical="center">
                  <Text variant="heading-strong-m" onBackground="brand-weak">01</Text>
                  <Heading as="h3" variant="heading-strong-m">{"Scoping & advice"}</Heading>
                </Row>
                <Text className={styles.skillCardDescription} onBackground="neutral-weak" variant="body-default-m">
                  {"Understanding requirements, goals and users, analysing constraints, advising on possible solutions, defining scope, estimating and planning."}</Text>
              </Column>
            </Card>
            <Card className={styles.skillCard} fillWidth background="surface" border="brand-alpha-weak" radius="l" padding="m" shadow="m">
              <Column className={styles.skillCardContent} fillWidth gap="12">
                <Row gap="12" vertical="center">
                  <Text variant="heading-strong-m" onBackground="brand-weak">02</Text>
                  <Heading as="h3" variant="heading-strong-m">{"Design & development"}</Heading>
                </Row>
                <Text className={styles.skillCardDescription} onBackground="neutral-weak" variant="body-default-m">
                  {"Functional and technical specifications, UX planning, interface design and tailored web development: applications, business websites, online stores and custom features."}</Text>
              </Column>
            </Card>
            <Card className={styles.skillCard} fillWidth background="surface" border="brand-alpha-weak" radius="l" padding="m" shadow="m">
              <Column className={styles.skillCardContent} fillWidth gap="12">
                <Row gap="12" vertical="center">
                  <Text variant="heading-strong-m" onBackground="brand-weak">03</Text>
                  <Heading as="h3" variant="heading-strong-m">{"Management & quality"}</Heading>
                </Row>
                <Text className={styles.skillCardDescription} onBackground="neutral-weak" variant="body-default-m">
                  {"Project organisation and tracking, prioritising requirements, managing changes, communicating with stakeholders, testing, acceptance testing and fixes before delivery."}</Text>
              </Column>
            </Card>
            <Card className={styles.skillCard} fillWidth background="surface" border="brand-alpha-weak" radius="l" padding="m" shadow="m">
              <Column className={styles.skillCardContent} fillWidth gap="12">
                <Row gap="12" vertical="center">
                  <Text variant="heading-strong-m" onBackground="brand-weak">04</Text>
                  <Heading as="h3" variant="heading-strong-m">{"Deployment & support"}</Heading>
                </Row>
                <Text className={styles.skillCardDescription} onBackground="neutral-weak" variant="body-default-m">
                  {"Deployment, environment configuration, documentation, user training and ongoing support to help the solution evolve over time."}</Text>
              </Column>
            </Card>
          </Grid>
        </Column>
      </Flex>

      <Flex fillWidth>
        <Column as="section" fillWidth gap="24" paddingX="l">
          <Row fillWidth horizontal="center" marginBottom="8">
            <Row gap="12" vertical="center">
              <Icon name="code" onBackground="brand-weak" />
              <Heading as="h2" variant="display-strong-xs" wrap="balance">{"My skills"}</Heading>
              <Line background="brand-alpha-weak" flex={1} />
            </Row>
          </Row>
          <Grid className={styles.skillsGrid} fillWidth gap="12" columns={3} m={{ columns: 2 }} s={{ columns: 1 }}>
            <Card className={styles.skillCard} fillWidth background="surface" border="brand-alpha-weak" radius="l" padding="m" shadow="m">
              <Column className={styles.skillCardContent} fillWidth gap="12">
                <Row gap="12" vertical="center">
                  <Icon name="code" onBackground="brand-weak" />
                  <Heading as="h3" variant="heading-strong-m">{"Full-Stack Development"}</Heading>
                </Row>
                <Text className={styles.skillCardDescription} onBackground="neutral-weak" variant="body-default-m">
                  HTML, CSS, JavaScript, PHP, Node.js, React, Vue.js, Next.js, Laravel, Symfony, Sylius, MySQL, Tailwind CSS.
                </Text>
              </Column>
            </Card>
            <Card className={styles.skillCard} fillWidth background="surface" border="brand-alpha-weak" radius="l" padding="m" shadow="m">
              <Column className={styles.skillCardContent} fillWidth gap="12">
                <Row gap="12" vertical="center">
                  <Icon name="wordpress" onBackground="brand-weak" />
                  <Heading as="h3" variant="heading-strong-m">CMS & e-commerce</Heading>
                </Row>
                <Text className={styles.skillCardDescription} onBackground="neutral-weak" variant="body-default-m">
                  {"WordPress, WooCommerce, PrestaShop, Shopify, WiziShop, development and integration of custom features."}</Text>
              </Column>
            </Card>
            <Card className={styles.skillCard} fillWidth background="surface" border="brand-alpha-weak" radius="l" padding="m" shadow="m">
              <Column className={styles.skillCardContent} fillWidth gap="12">
                <Row gap="12" vertical="center">
                  <Icon name="settings" onBackground="brand-weak" />
                  <Heading as="h3" variant="heading-strong-m">{"Project management"}</Heading>
                </Row>
                <Text className={styles.skillCardDescription} onBackground="neutral-weak" variant="body-default-m">
                  {"Requirements analysis, project specifications, functional and technical specifications, cost estimation, planning, project tracking, acceptance testing, Agile, Scrum and Kanban, Jira and Linear."}</Text>
              </Column>
            </Card>
            <Card className={styles.skillCard} fillWidth background="surface" border="brand-alpha-weak" radius="l" padding="m" shadow="m">
              <Column className={styles.skillCardContent} fillWidth gap="12">
                <Row gap="12" vertical="center">
                  <Icon name="seo" onBackground="brand-weak" />
                  <Heading as="h3" variant="heading-strong-m">{"Product, UX & quality"}</Heading>
                </Row>
                <Text className={styles.skillCardDescription} onBackground="neutral-weak" variant="body-default-m">
                  {"User experience, Figma, journey optimisation, web performance, accessibility, technical SEO and continuous improvement."}</Text>
              </Column>
            </Card>
            <Card className={styles.skillCard} fillWidth background="surface" border="brand-alpha-weak" radius="l" padding="m" shadow="m">
              <Column className={styles.skillCardContent} fillWidth gap="12">
                <Row gap="12" vertical="center">
                  <Icon name="tools" onBackground="brand-weak" />
                  <Heading as="h3" variant="heading-strong-m">{"Tools & automation"}</Heading>
                </Row>
                <Text className={styles.skillCardDescription} onBackground="neutral-weak" variant="body-default-m">
                  {"Git, deployment and hosting tools, n8n, ChatGPT, Cursor and AI tools integrated into development workflows."}</Text>
              </Column>
            </Card>
          </Grid>
        </Column>
      </Flex>

      <Flex fillWidth>
        <Column as="section" fillWidth gap="24" paddingX="l">
          <Row fillWidth horizontal="center" marginBottom="8">
            <Row gap="12" vertical="center">
              <Icon name="person" onBackground="brand-weak" />
              <Heading as="h2" variant="display-strong-xs" wrap="balance">{"Bringing development and project management together"}</Heading>
              <Line background="brand-alpha-weak" flex={1} />
            </Row>
          </Row>
          <Text onBackground="neutral-weak" variant="body-default-l">
            {"My full-stack development background gives me a practical understanding of technical constraints, helps me assess feasibility and communicate effectively with development teams."}</Text>
          <Text onBackground="neutral-weak" variant="body-default-l">
            {"As a freelancer, I have also managed projects independently: understanding requirements, recommendations, proposals, planning, development, client communication, acceptance testing, delivery and maintenance."}</Text>
          <Text onBackground="neutral-weak" variant="body-default-l">
            {"Teaching web development has taught me to make technical topics accessible, adapt my explanations to different audiences and help users get started with their tools."}</Text>
          <Row fillWidth horizontal="center" paddingTop="12">
            <Button href="/en/contact" variant="primary" size="m" arrowIcon>
              {"🚀 Let's talk today"}</Button>
          </Row>
        </Column>
      </Flex>

      <Flex>
        <Column fillWidth paddingX="l">
          <Card
            className={styles.portfolioCta}
            background="surface"
            border="brand-alpha-weak"
            radius="l"
            padding="xl"
            shadow="m"
          >
            <Row
              fillWidth
              horizontal="between"
              vertical="center"
              s={{ direction: "column", horizontal: "start" }}
              gap="16"
            >
              <Column gap="12">
                <Row gap="12" vertical="center">
                  <Icon name="rocket" onBackground="brand-weak" />
                  <Text variant="heading-strong-xl">{"Explore my portfolio"}</Text>
                </Row>
                <Text variant="body-default-l" onBackground="neutral-weak">
                  {"Business websites, online stores, applications and custom features: explore selected projects I have helped develop, design, optimise or manage."}</Text>
                <Text variant="body-default-l" onBackground="neutral-weak">
                  {"Every project shares the same goal: turn a real need into a useful, reliable solution tailored to its users."}</Text>
              </Column>
              <Button href="/en/work" variant="primary" size="m" arrowIcon>
                {"View portfolio"}</Button>
            </Row>
          </Card>
        </Column>
      </Flex>
    </Column>
  );
}
